# -*- coding: utf-8 -*-
"""Advanced Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwNpT19vaIpjgwUtMx5v2dMm7zqa5Lsc
"""

import math

history = []


def calculator():
    while True:
        print("\n" + "=" * 45)
        print("          ADVANCED CALCULATOR")
        print("=" * 45)

        print("""
1.  Addition
2.  Subtraction
3.  Multiplication
4.  Division
5.  Power
6.  Square Root
7.  Percentage
8.  Modulus
9.  Factorial
10. Sine
11. Cosine
12. Tangent
13. Log10
14. Natural Log
15. History
16. Clear History
0. Exit
""")

        choice = input("Enter your choice (0-16): ").strip()

        # EXIT
        if choice == "0":
            print("\nCalculator closed.")
            break

        # HISTORY
        elif choice == "15":
            print("\n----- CALCULATION HISTORY -----")

            if not history:
                print("No calculations yet.")
            else:
                for i, item in enumerate(history, 1):
                    print(f"{i}. {item}")

        # CLEAR HISTORY
        elif choice == "16":
            history.clear()
            print("History cleared.")

        # ADDITION
        elif choice == "1":
            try:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                result = a + b

                print(f"Result: {result}")
                history.append(f"{a} + {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # SUBTRACTION
        elif choice == "2":
            try:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                result = a - b

                print(f"Result: {result}")
                history.append(f"{a} - {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # MULTIPLICATION
        elif choice == "3":
            try:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                result = a * b

                print(f"Result: {result}")
                history.append(f"{a} × {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # DIVISION
        elif choice == "4":
            try:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                if b == 0:
                    print("Cannot divide by zero.")
                else:
                    result = a / b

                    print(f"Result: {result}")
                    history.append(f"{a} ÷ {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # POWER
        elif choice == "5":
            try:
                a = float(input("Enter base: "))
                b = float(input("Enter exponent: "))

                result = a ** b

                print(f"Result: {result}")
                history.append(f"{a} ^ {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # SQUARE ROOT
        elif choice == "6":
            try:
                a = float(input("Enter number: "))

                if a < 0:
                    print("Square root of a negative number is not real.")
                else:
                    result = math.sqrt(a)

                    print(f"Result: {result}")
                    history.append(f"√{a} = {result}")

            except ValueError:
                print("Invalid number.")

        # PERCENTAGE
        elif choice == "7":
            try:
                number = float(input("Enter number: "))
                percentage = float(input("Enter percentage: "))

                result = number * percentage / 100

                print(f"{percentage}% of {number} = {result}")
                history.append(
                    f"{percentage}% of {number} = {result}"
                )

            except ValueError:
                print("Invalid number.")

        # MODULUS
        elif choice == "8":
            try:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                if b == 0:
                    print("Cannot use zero.")
                else:
                    result = a % b

                    print(f"Result: {result}")
                    history.append(f"{a} % {b} = {result}")

            except ValueError:
                print("Invalid number.")

        # FACTORIAL
        elif choice == "9":
            try:
                a = int(input("Enter a whole number: "))

                if a < 0:
                    print("Factorial cannot be negative.")
                else:
                    result = math.factorial(a)

                    print(f"Result: {result}")
                    history.append(f"{a}! = {result}")

            except ValueError:
                print("Enter a whole number only.")

        # SINE
        elif choice == "10":
            try:
                angle = float(input("Enter angle in degrees: "))

                result = math.sin(math.radians(angle))

                print(f"sin({angle}°) = {result}")
                history.append(f"sin({angle}°) = {result}")

            except ValueError:
                print("Invalid number.")

        # COSINE
        elif choice == "11":
            try:
                angle = float(input("Enter angle in degrees: "))

                result = math.cos(math.radians(angle))

                print(f"cos({angle}°) = {result}")
                history.append(f"cos({angle}°) = {result}")

            except ValueError:
                print("Invalid number.")

        # TANGENT
        elif choice == "12":
            try:
                angle = float(input("Enter angle in degrees: "))

                result = math.tan(math.radians(angle))

                print(f"tan({angle}°) = {result}")
                history.append(f"tan({angle}°) = {result}")

            except ValueError:
                print("Invalid number.")

        # LOG10
        elif choice == "13":
            try:
                number = float(input("Enter number: "))

                if number <= 0:
                    print("Log requires a positive number.")
                else:
                    result = math.log10(number)

                    print(f"log10({number}) = {result}")
                    history.append(
                        f"log10({number}) = {result}"
                    )

            except ValueError:
                print("Invalid number.")

        # NATURAL LOG
        elif choice == "14":
            try:
                number = float(input("Enter number: "))

                if number <= 0:
                    print("Natural log requires a positive number.")
                else:
                    result = math.log(number)

                    print(f"ln({number}) = {result}")
                    history.append(
                        f"ln({number}) = {result}"
                    )

            except ValueError:
                print("Invalid number.")

        else:
            print("Invalid choice. Enter a number from 0 to 16.")


# Start calculator
calculator()